In [1]:
from pyexpat import features

print("Ca commence")

Ca commence

In [2]:
import yfinance as YF
import numpy as np
import pandas as pd

In [3]:
try:
    data = YF.download("AAPL", start="2020-01-01", end="2023-01-01")
    if data.empty:
        raise ValueError("No data")
    data.to_csv('AAPL.csv')
    print("✅ Données téléchargées et sauvegardées")
except Exception as e:
    print(f"Une erreur est survenue {e}")
    data = pd.read_csv("AAPL.csv")
    print("📂 Données chargées depuis le CSV")

[*********************100%***********************]  1 of 1 completed

✅ Données téléchargées et sauvegardées

In [4]:
data.columns= data.columns.get_level_values(0)
data=data.dropna()

In [5]:
data["Return"] = data["Close"].pct_change()

In [6]:
data

Price,Close,High,Low,Open,Volume,Return
Date,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,NaN
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.009722
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086
...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469

In [7]:
data["MA_20"]= data["Close"].rolling(20).mean()
data

Price,Close,High,Low,Open,Volume,Return,MA_20
Date,,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,NaN,NaN
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.009722,NaN
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968,NaN
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703,NaN
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086,NaN
...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136

In [8]:
data["MA_50"]= data["Close"].rolling(50).mean()

In [9]:
data["MA_200"]=data["Close"].rolling(200).mean()

In [10]:
data["Volatility"]= data["Return"].rolling(20).std()

momentum
MA ratio
RSI
volume change
distance to MA

In [11]:
data["Momentum"]=data["Close"].pct_change(periods=10)
data

Price,Close,High,Low,Open,Volume,Return,MA_20,MA_50,MA_200,Volatility,Momentum
Date,,,,,,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.009722,NaN,NaN,NaN,NaN,NaN
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968,NaN,NaN,NaN,NaN,NaN
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703,NaN,NaN,NaN,NaN,NaN
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958,141.785299,149.372269,0.020904,-0.072454
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655,141.625447,149.254148,0.020438,-0.100076
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094,141.307857,149.136525,0.020940,-0.133567
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630,141.034207,149.014573,0.018540,-0.094965
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136,140.764694,148.872151,0.018554,-0.048132

In [12]:
data["MA_ratio"]=data["MA_20"]/data["MA_50"]

In [13]:
data

Price,Close,High,Low,Open,Volume,Return,MA_20,MA_50,MA_200,Volatility,Momentum,MA_ratio
Date,,,,,,,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.009722,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958,141.785299,149.372269,0.020904,-0.072454,0.976413
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655,141.625447,149.254148,0.020438,-0.100076,0.972584
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094,141.307857,149.136525,0.020940,-0.133567,0.969501
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630,141.034207,149.014573,0.018540,-0.094965,0.964955
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136,140.764694,148.872151,0.018554,-0.048132,0.960377

In [14]:
def calculate_rsi(data, period=14):
    # Calculer les variations de prix
    delta = data['Close'].diff()

    # Séparer gains et pertes
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)

    # Calculer les moyennes mobiles
    avg_gain = gain.rolling(window=period).mean()
    avg_loss = loss.rolling(window=period).mean()

    # Calculer RS et RSI
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))

    return rsi

# Appliquer la fonction
data["RSI"] = calculate_rsi(data, period=14)

In [15]:
data

Price,Close,High,Low,Open,Volume,Return,MA_20,MA_50,MA_200,Volatility,Momentum,MA_ratio,RSI
Date,,,,,,,,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.009722,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958,141.785299,149.372269,0.020904,-0.072454,0.976413,26.261572
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655,141.625447,149.254148,0.020438,-0.100076,0.972584,27.960254
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094,141.307857,149.136525,0.020940,-0.133567,0.969501,26.152298
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630,141.034207,149.014573,0.018540,-0.094965,0.964955,30.302152
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136,140.764694,148.872151,0.018554,-0.048132,0.960377,31.430287

In [16]:
data["Volume_Change"] = data["Volume"].pct_change()
data

Price,Close,High,Low,Open,Volume,Return,MA_20,MA_50,MA_200,Volatility,Momentum,MA_ratio,RSI,Volume_Change
Date,,,,,,,,,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.009722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080029
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.190918
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.080374
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.213160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958,141.785299,149.372269,0.020904,-0.072454,0.976413,26.261572,-0.180306
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655,141.625447,149.254148,0.020438,-0.100076,0.972584,27.960254,0.081374
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094,141.307857,149.136525,0.020940,-0.133567,0.969501,26.152298,0.238098
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630,141.034207,149.014573,0.018540,-0.094965,0.964955,30.302152,-0.113938
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136,140.764694,148.872151,0.018554,-0.048132,0.960377,31.430287,0.017575

In [17]:
data["Distance_to_MA"]=((data["Close"] - data["MA_50"])/data["MA_50"])

In [18]:
data

Price,Close,High,Low,Open,Volume,Return,MA_20,MA_50,MA_200,Volatility,Momentum,MA_ratio,RSI,Volume_Change,Distance_to_MA
Date,,,,,,,,,,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.009722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080029,NaN
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.190918,NaN
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.080374,NaN
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.213160,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958,141.785299,149.372269,0.020904,-0.072454,0.976413,26.261572,-0.180306,-0.084680
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655,141.625447,149.254148,0.020438,-0.100076,0.972584,27.960254,0.081374,-0.096365
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094,141.307857,149.136525,0.020940,-0.133567,0.969501,26.152298,0.238098,-0.122124
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630,141.034207,149.014573,0.018540,-0.094965,0.964955,30.302152,-0.113938,-0.095507
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136,140.764694,148.872151,0.018554,-0.048132,0.960377,31.430287,0.017575,-0.091538

In [19]:
data= data.dropna()
data

Price,Close,High,Low,Open,Volume,Return,MA_20,MA_50,MA_200,Volatility,Momentum,MA_ratio,RSI,Volume_Change,Distance_to_MA
Date,,,,,,,,,,,,,,,
2020-10-15,117.193382,117.669105,114.707965,115.261359,112559200,-0.003961,111.411872,113.512733,85.802222,0.027202,0.033564,0.981492,63.102249,-0.253150,0.032425
2020-10-16,115.552612,118.008913,115.348731,117.746774,115393800,-0.014001,112.003130,113.616082,86.017983,0.026219,0.053088,0.985803,56.510527,0.025183,0.017045
2020-10-19,112.601196,116.911842,112.290519,116.465244,120639300,-0.025542,112.289537,113.710596,86.222505,0.026436,-0.004463,0.987503,52.833615,0.045457,-0.009756
2020-10-20,114.086594,115.513769,112.261359,112.814753,124423700,0.013192,112.566233,113.803459,86.431599,0.026378,0.038441,0.989128,52.563329,0.031370,0.002488
2020-10-21,113.465248,115.251640,113.057478,113.271070,89946000,-0.005446,113.039531,113.948992,86.639285,0.024299,0.015554,0.992019,50.121850,-0.277099,-0.004245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958,141.785299,149.372269,0.020904,-0.072454,0.976413,26.261572,-0.180306,-0.084680
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655,141.625447,149.254148,0.020438,-0.100076,0.972584,27.960254,0.081374,-0.096365
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094,141.307857,149.136525,0.020940,-0.133567,0.969501,26.152298,0.238098,-0.122124
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630,141.034207,149.014573,0.018540,-0.094965,0.964955,30.302152,-0.113938,-0.095507
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136,140.764694,148.872151,0.018554,-0.048132,0.960377,31.430287,0.017575,-0.091538

In [20]:
data.to_csv('AAPL_with_indicators.csv')

In [21]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Création d'une figure avec des lignes de hauteurs différentes
fig = make_subplots(rows=3, cols=1, shared_xaxes=True,
                    vertical_spacing=0.05,
                    subplot_titles=('AAPL - Prix & MAs', 'RSI', 'Distance à la MA 50'),
                    row_heights=[0.5, 0.25, 0.25])

# 1. Graphique du Prix (Candlestick)
fig.add_trace(go.Scatter(x=data.index, y=data['Close'], name='Close', line=dict(color='black')), row=1, col=1)
fig.add_trace(go.Scatter(x=data.index, y=data['MA_20'], name='MA 20', line=dict(dash='dash')), row=1, col=1)
fig.add_trace(go.Scatter(x=data.index, y=data['MA_50'], name='MA 50'), row=1, col=1)

# 2. RSI
fig.add_trace(go.Scatter(x=data.index, y=data['RSI'], name='RSI', line=dict(color='purple')), row=2, col=1)
fig.add_hline(y=70, line_dash="dot", line_color="red", row=2, col=1)
fig.add_hline(y=30, line_dash="dot", line_color="green", row=2, col=1)

# 3. Distance à la MA (Indicateur d'étirement)
fig.add_trace(go.Bar(x=data.index, y=data['Distance_to_MA'], name='Dist MA 50'), row=3, col=1)

# Mise en page
fig.update_layout(height=800, title_text="Analyse Technique Interactive - AAPL", showlegend=True)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'line': {'color': 'black'},
              'name': 'Close',
              'type': 'scatter',
              'x': array(['2020-10-15T00:00:00.000000000', '2020-10-16T00:00:00.000000000',
                          '2020-10-19T00:00:00.000000000', ..., '2022-12-28T00:00:00.000000000',
                          '2022-12-29T00:00:00.000000000', '2022-12-30T00:00:00.000000000'],
                         shape=(557,), dtype='datetime64[ns]'),
              'xaxis': 'x',
              'y': {'bdata': ('AAAAYGBMXUAAAAAAXuNcQAAAAAB6Jl' ... 'A+A19AAAAA4B7kX0AAAAAAR/hfQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'line': {'dash': 'dash'},
              'name': 'MA 20',
              'type': 'scatter',
              'x': array(['2020-10-15T00:00:00.000000000', '2020-10-16T00:00:00.000000000',
                          '2020-10-19T00:00:00.000000000', ..., '2022-12-28T00:00:00.000000000',
                          '2022-12-29T00:00:00.000000000', '2022-12-30T00:00:00.000000000'],
                         shape=(557,), dtype='datetime64[ns]'),
              'xaxis': 'x',
              'y': {'bdata': ('zczMHFzaW0AAAABIMwBcQM3MzMSHEl' ... 'PwH2FAZmZmou4CYUAAAAAE/eVgQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'name': 'MA 50',
              'type': 'scatter',
              'x': array(['2020-10-15T00:00:00.000000000', '2020-10-16T00:00:00.000000000',
                          '2020-10-19T00:00:00.000000000', ..., '2022-12-28T00:00:00.000000000',
                          '2022-12-29T00:00:00.000000000', '2022-12-30T00:00:00.000000000'],
                         shape=(557,), dtype='datetime64[ns]'),
              'xaxis': 'x',
              'y': {'bdata': ('9ihcn9BgXEAzMzPjbWdcQHsUrmd6bV' ... 'bZqWFAFK5HORihYUCF61FgeJhhQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'line': {'color': 'purple'},
              'name': 'RSI',
              'type': 'scatter',
              'x': array(['2020-10-15T00:00:00.000000000', '2020-10-16T00:00:00.000000000',
                          '2020-10-19T00:00:00.000000000', ..., '2022-12-28T00:00:00.000000000',
                          '2022-12-29T00:00:00.000000000', '2022-12-30T00:00:00.000000000'],
                         shape=(557,), dtype='datetime64[ns]'),
              'xaxis': 'x2',
              'y': {'bdata': ('KlRDfxaNT0Da72PzWEFMQKlKweKzak' ... 'P9JjpA5JrU0FlNPkAcSqBMJ24/QA=='),
                    'dtype': 'f8'},
              'yaxis': 'y2'},
             {'name': 'Dist MA 50',
              'type': 'bar',
              'x': array(['2020-10-15T00:00:00.000000000', '2020-10-16T00:00:00.000000000',
                          '2020-10-19T00:00:00.000000000', ..., '2022-12-28T00:00:00.000000000',
                          '2022-12-29T00:00:00.000000000', '2022-12-30T00:00:00.000000000'],
                         shape=(557,), dtype='datetime64[ns]'),
              'xaxis': 'x3',
              'y': {'bdata': ('D42ZCQKaoD9IVqeeHXSRPxAlxVsi+4' ... 'OMQ7+/LOKTuC1zuL9gD0zWDW+3vw=='),
                    'dtype': 'f8'},
              'yaxis': 'y3'}],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': 'AAPL - Prix & MAs',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'RSI',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.5,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Distance à la MA 50',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.225,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'height': 800,
               'shapes': [{'line': {'color': 'red', 'dash': 'dot'},
                           'type': 'line',
                           'x0': 0,
                           'x1': 1,
                           'xref': 'x2 domain',
                           'y0': 70,
                           'y1': 70,
                           'yref': 'y2'},
                          {'line': {'color': 'green', 'dash': 'dot'},
                           'type': 'line',
                           'x0': 0,
                           'x1': 1,
                           'xref': 'x2 domain',
                           'y0': 30,
                           'y1': 30,
                           'yref': 'y2'}],
               'showlegend': True,
               'template': '...',
               'title': {'text': 'Analyse Technique Interactive - AAPL'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'matches': 'x3', 'showticklabels': False},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x3', 'showticklabels': False},
               'xaxis3': {'anchor': 'y3', 'domain': [0.0, 1.0]},
               'yaxis': {'anchor': 'x', 'domain': [0.55, 1.0]},
               'yaxis2': {'anchor': 'x2', 'domain': [0.275, 0.5]},
               'yaxis3': {'anchor': 'x3', 'domain': [0.0, 0.225]}}
})

In [22]:
data["Target"]= (data["Close"]>data["Close"].shift(-7))
data

/tmp/ipykernel_15718/1813667923.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Price,Close,High,Low,Open,Volume,Return,MA_20,MA_50,MA_200,Volatility,Momentum,MA_ratio,RSI,Volume_Change,Distance_to_MA,Target
Date,,,,,,,,,,,,,,,,
2020-10-15,117.193382,117.669105,114.707965,115.261359,112559200,-0.003961,111.411872,113.512733,85.802222,0.027202,0.033564,0.981492,63.102249,-0.253150,0.032425,True
2020-10-16,115.552612,118.008913,115.348731,117.746774,115393800,-0.014001,112.003130,113.616082,86.017983,0.026219,0.053088,0.985803,56.510527,0.025183,0.017045,True
2020-10-19,112.601196,116.911842,112.290519,116.465244,120639300,-0.025542,112.289537,113.710596,86.222505,0.026436,-0.004463,0.987503,52.833615,0.045457,-0.009756,True
2020-10-20,114.086594,115.513769,112.261359,112.814753,124423700,0.013192,112.566233,113.803459,86.431599,0.026378,0.038441,0.989128,52.563329,0.031370,0.002488,True
2020-10-21,113.465248,115.251640,113.057478,113.271070,89946000,-0.005446,113.039531,113.948992,86.639285,0.024299,0.015554,0.992019,50.121850,-0.277099,-0.004245,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,129.778854,130.330013,127.593891,128.853688,63814900,-0.002798,138.440958,141.785299,149.372269,0.020904,-0.072454,0.976413,26.261572,-0.180306,-0.084680,False
2022-12-27,127.977760,129.335985,126.688438,129.306460,69007800,-0.013878,137.742655,141.625447,149.254148,0.020438,-0.100076,0.972584,27.960254,0.081374,-0.096365,False
2022-12-28,124.050713,128.961953,123.883397,127.623418,85438400,-0.030685,136.998094,141.307857,149.136525,0.020940,-0.133567,0.969501,26.152298,0.238098,-0.122124,False
2022-12-29,127.564384,128.420649,125.714059,125.969950,75703700,0.028324,136.091630,141.034207,149.014573,0.018540,-0.094965,0.964955,30.302152,-0.113938,-0.095507,False
2022-12-30,127.879333,127.899022,125.418798,126.383334,77034200,0.002469,135.187136,140.764694,148.872151,0.018554,-0.048132,0.960377,31.430287,0.017575,-0.091538,False

In [23]:
data["Target"]=data["Target"].astype(int)

/tmp/ipykernel_15718/2171523485.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
data.

In [24]:
taille= int(len(data)*0.8)

train=data[:taille]
test=data[taille:]

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

accuracy = []
precision = []
recall = []
f1= []
features= ["Return","Volatility","Momentum","MA_ratio","Volume_Change","RSI","Distance_to_MA"]
ts=TimeSeriesSplit(n_splits=5)
X=data[features]
Y=data["Target"]

for i,j in ts.split(X):
    model = RandomForestClassifier(random_state=42)
    x_train=X.iloc[i]
    y_train=Y.iloc[i]
    x_test=X.iloc[j]
    y_test=Y.iloc[j]
    model.fit(x_train, y_train)
    prediction = model.predict(x_test)
    accuracy.append(accuracy_score(y_test, prediction))
    precision.append(precision_score(y_test, prediction))
    recall.append(recall_score(y_test, prediction))
    f1.append(f1_score(y_test, prediction))

In [31]:
for i,j in enumerate(accuracy):
    print(f"le modele {i}  a {j} de accuracy")

le 0 a 0.45652173913043476 de accuracy
le 1 a 0.5760869565217391 de accuracy
le 2 a 0.45652173913043476 de accuracy
le 3 a 0.5652173913043478 de accuracy
le 4 a 0.5217391304347826 de accuracy

In [32]:
for i,j in enumerate(precision):
    print(f"le modele {i}  a {j} de precision")

le modele 0  a 0.2222222222222222 de precision
le modele 1  a 0.3684210526315789 de precision
le modele 2  a 0.47368421052631576 de precision
le modele 3  a 0.5 de precision
le modele 4  a 0.7142857142857143 de precision

In [33]:
for i,j in enumerate(recall):
    print(f"le modele {i}  a {j} de recall")

le modele 0  a 0.26666666666666666 de recall
le modele 1  a 0.20588235294117646 de recall
le modele 2  a 0.375 de recall
le modele 3  a 0.475 de recall
le modele 4  a 0.423728813559322 de recall

In [34]:
for i,j in enumerate(f1):
    print(f"le modele {i}  a {j} de f1_score")

le modele 0  a 0.24242424242424243 de f1_score
le modele 1  a 0.2641509433962264 de f1_score
le modele 2  a 0.4186046511627907 de f1_score
le modele 3  a 0.48717948717948717 de f1_score
le modele 4  a 0.5319148936170213 de f1_score

In [26]:
print(f"Accuracy moyenne : {np.mean(accuracy):.2f} ecart-type : {np.std(accuracy):.2f}")
print(f"F1-Score moyen : {np.mean(f1):.2f} ecart-type : {np.std(f1):.2f}")
print(f"Precision moyenne : {np.mean(precision):.2f} ecart-type : {np.std(precision):.2f}")
print(f"Recall moyenne : {np.mean(recall):.2f}  ecart-type : {np.std(recall):.2f} ")

Accuracy moyenne : 0.52 ecart-type : 0.05
F1-Score moyen : 0.39 ecart-type : 0.12
Precision moyenne : 0.46 ecart-type : 0.16
Recall moyenne : 0.35  ecart-type : 0.10

Backtesting

Tableau des metrique du modele

In [36]:
tableau_metrique=[]
for i in range(5):
    tab=[]
    tab.append(i+1)
    tab.append(accuracy[i])
    tab.append(precision[i])
    tab.append(recall[i])
    tab.append(f1[i])
    tableau_metrique.append(tab)

pd_metrique= pd.DataFrame(tableau_metrique, columns=["Modele","Accuracy","Precision","Recall","F1"])
pd_metrique

   Modele  Accuracy  Precision    Recall        F1
0       1  0.456522   0.222222  0.266667  0.242424
1       2  0.576087   0.368421  0.205882  0.264151
2       3  0.456522   0.473684  0.375000  0.418605
3       4  0.565217   0.500000  0.475000  0.487179
4       5  0.521739   0.714286  0.423729  0.531915

In [29]:
data_test= data.copy()